version:     "0029a--12-Sep-2022"
copyright:   "2022"
author:      "Clarissa Thea Aryanto"
title:       "OS222: Operating Systems 2022-2"
githublink:  "https://github.com/luluorv/os222/"
myloglink:   "/TXT/mylog.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]